# Generated by Django 5.0.1 on 2024-09-30 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_marvel_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marvel',
            name='city',
        ),
    ]
