# Generated by Django 5.0.1 on 2024-09-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_marvel_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='marvel',
            name='city',
            field=models.CharField(default='NYC', max_length=50),
        ),
    ]
