# Generated by Django 5.0.1 on 2024-09-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_m'),
    ]

    operations = [
        migrations.AddField(
            model_name='marvel',
            name='city',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
